{
    "en": {
        "System Health Configuration": "System Health Configuration",
        "General Settings": "General Settings",
        "Check interval (hours)": "Check interval (hours)",
        "How often to run health checks (1-168 hours)": "How often to run health checks (1-168 hours)",
        "Memory Monitoring": "Memory Monitoring",
        "Enable memory monitoring": "Enable memory monitoring",
        "Memory warning threshold (MB)": "Memory warning threshold (MB)",
        "Alert when free memory drops below this value": "Alert when free memory drops below this value",
        "Disk Monitoring": "Disk Monitoring",
        "Enable disk monitoring": "Enable disk monitoring",
        "Disk warning threshold (%)": "Disk warning threshold (%)",
        "Alert when disk usage exceeds this percentage": "Alert when disk usage exceeds this percentage",
        "Adapter Crash Detection": "Adapter Crash Detection",
        "Enable adapter crash detection": "Enable adapter crash detection",
        "State Inspector": "State Inspector",
        "Enable orphaned state detection": "Enable orphaned state detection",
        "Enable duplicate state detection": "Enable duplicate state detection",
        "Duplicate similarity threshold": "Duplicate similarity threshold",
        "How similar state names must be to be flagged (0.5-1.0)": "How similar state names must be to be flagged (0.5-1.0)",
        "Enable stale state detection": "Enable stale state detection",
        "Stale threshold (hours)": "Stale threshold (hours)",
        "Consider states stale if not updated within this time": "Consider states stale if not updated within this time"
    },
    "de": {
        "System Health Configuration": "Systemgesundheit Konfiguration",
        "General Settings": "Allgemeine Einstellungen",
        "Check interval (hours)": "Prüfintervall (Stunden)",
        "How often to run health checks (1-168 hours)": "Wie oft Gesundheitsprüfungen durchgeführt werden (1-168 Stunden)",
        "Memory Monitoring": "Speicherüberwachung",
        "Enable memory monitoring": "Speicherüberwachung aktivieren",
        "Memory warning threshold (MB)": "Speicher-Warnschwelle (MB)",
        "Alert when free memory drops below this value": "Warnung wenn freier Speicher unter diesen Wert fällt",
        "Disk Monitoring": "Festplattenüberwachung",
        "Enable disk monitoring": "Festplattenüberwachung aktivieren",
        "Disk warning threshold (%)": "Festplatten-Warnschwelle (%)",
        "Alert when disk usage exceeds this percentage": "Warnung wenn Festplattennutzung diesen Prozentsatz überschreitet",
        "Adapter Crash Detection": "Adapter-Absturzerkennung",
        "Enable adapter crash detection": "Adapter-Absturzerkennung aktivieren",
        "State Inspector": "Datenpunkt-Inspektor",
        "Enable orphaned state detection": "Verwaiste Datenpunkte erkennen",
        "Enable duplicate state detection": "Duplikate erkennen",
        "Duplicate similarity threshold": "Duplikat-Ähnlichkeitsschwelle",
        "How similar state names must be to be flagged (0.5-1.0)": "Wie ähnlich Datenpunktnamen sein müssen (0.5-1.0)",
        "Enable stale state detection": "Veraltete Datenpunkte erkennen",
        "Stale threshold (hours)": "Veraltet-Schwelle (Stunden)",
        "Consider states stale if not updated within this time": "Datenpunkte als veraltet markieren wenn nicht innerhalb dieser Zeit aktualisiert"
    }
}
